import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const servers = [
  // ─── OFICIALES ANTHROPIC ───────────────────────────────────────────────────
  {
    slug: "filesystem",
    name: "Filesystem",
    description: "Read and write files on your local filesystem with full path control.",
    longDesc: "Provides tools to read, write, move, and search files and directories. Essential for any workflow that requires file manipulation.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-filesystem",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["filesystem", "files", "official"]),
    tools: JSON.stringify(["read_file", "write_file", "list_directory", "create_directory", "move_file", "search_files"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 4800,
    verified: true,
    featured: true,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-filesystem /path/to/dir",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-filesystem", "/Users/username"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "github",
    name: "GitHub",
    description: "Interact with GitHub repositories — issues, PRs, files, and search.",
    longDesc: "Full access to GitHub API: create issues, open pull requests, search code, read files from any repo, manage branches and more.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-github",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["git", "github", "api", "official"]),
    tools: JSON.stringify(["create_issue", "create_pull_request", "get_file_contents", "list_repos", "search_code", "create_branch"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 5200,
    verified: true,
    featured: true,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-github",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-github"], env: { GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_PERSONAL_ACCESS_TOKEN}" } }),
    envVars: JSON.stringify([{ name: "GITHUB_PERSONAL_ACCESS_TOKEN", description: "GitHub Personal Access Token con permisos repo", required: true, example: "ghp_xxxxxxxxxxxx" }]),
  },
  {
    slug: "postgres",
    name: "PostgreSQL",
    description: "Read-only query access to PostgreSQL databases with schema inspection.",
    longDesc: "Connect to any PostgreSQL database, run read-only SQL queries, inspect schemas and table structures. Perfect for data exploration and analysis.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-postgres",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["database", "sql", "postgres", "official"]),
    tools: JSON.stringify(["query", "list_tables", "describe_table"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 3100,
    verified: true,
    featured: true,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-postgres",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-postgres", "${POSTGRES_CONNECTION_STRING}"] }),
    envVars: JSON.stringify([{ name: "POSTGRES_CONNECTION_STRING", description: "PostgreSQL connection string", required: true, example: "postgresql://user:pass@localhost:5432/mydb" }]),
  },
  {
    slug: "brave-search",
    name: "Brave Search",
    description: "Web and local search using the Brave Search API.",
    longDesc: "Search the web and local files using Brave Search. Provides real-time web results without tracking.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-brave-search",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["search", "web", "api", "official"]),
    tools: JSON.stringify(["brave_web_search", "brave_local_search"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 2800,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-brave-search",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-brave-search"], env: { BRAVE_API_KEY: "${BRAVE_API_KEY}" } }),
    envVars: JSON.stringify([{ name: "BRAVE_API_KEY", description: "Brave Search API key", required: true, example: "BSA..." }]),
  },
  {
    slug: "git",
    name: "Git",
    description: "Git repository operations — log, diff, blame, status and more.",
    longDesc: "Full git operations on local repositories: read history, diffs, blame, branches, stashes and commits without leaving your AI assistant.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-git",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["git", "version-control", "official"]),
    tools: JSON.stringify(["git_log", "git_diff", "git_blame", "git_status", "git_show"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 2400,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-git",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-git"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "memory",
    name: "Memory",
    description: "Knowledge graph-based persistent memory across conversations.",
    longDesc: "Stores and retrieves information using a knowledge graph. Lets your AI assistant remember facts, relationships, and context across sessions.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-memory",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["memory", "knowledge-graph", "official"]),
    tools: JSON.stringify(["create_entities", "create_relations", "add_observations", "search_nodes", "read_graph"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 3600,
    verified: true,
    featured: true,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-memory",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-memory"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "fetch",
    name: "Fetch",
    description: "Fetch web content and convert it to markdown for easy reading.",
    longDesc: "Retrieve any URL and get its content converted to clean markdown. Handles JavaScript-rendered pages via Puppeteer.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-fetch",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["web", "fetch", "scraping", "official"]),
    tools: JSON.stringify(["fetch"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 2100,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-fetch",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-fetch"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "sqlite",
    name: "SQLite",
    description: "Full SQLite database operations — read, write, and schema management.",
    longDesc: "Create, query, and manage SQLite databases. Supports schema inspection, read/write operations and business intelligence queries.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-sqlite",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["database", "sql", "sqlite", "official"]),
    tools: JSON.stringify(["read_query", "write_query", "list_tables", "describe_table", "create_table"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1900,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-sqlite",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-sqlite", "/path/to/database.db"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "slack",
    name: "Slack",
    description: "Read and post messages, manage channels and users in Slack.",
    longDesc: "Full Slack integration: read channel history, post messages, list users and channels, upload files and manage your workspace.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-slack",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["communication", "slack", "api", "official"]),
    tools: JSON.stringify(["slack_post_message", "slack_list_channels", "slack_get_channel_history", "slack_list_users"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1700,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-slack",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-slack"], env: { SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}", SLACK_TEAM_ID: "${SLACK_TEAM_ID}" } }),
    envVars: JSON.stringify([
      { name: "SLACK_BOT_TOKEN", description: "Bot User OAuth Token", required: true, example: "xoxb-..." },
      { name: "SLACK_TEAM_ID", description: "Slack workspace Team ID", required: true, example: "T01234ABCD" },
    ]),
  },
  {
    slug: "puppeteer",
    name: "Puppeteer",
    description: "Browser automation — navigate, click, screenshot, and scrape websites.",
    longDesc: "Control a headless Chromium browser to automate web interactions: navigate pages, click buttons, fill forms, take screenshots and extract content.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-puppeteer",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["browser", "automation", "scraping", "official"]),
    tools: JSON.stringify(["puppeteer_navigate", "puppeteer_click", "puppeteer_screenshot", "puppeteer_fill", "puppeteer_evaluate"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 2900,
    verified: true,
    featured: true,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-puppeteer",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-puppeteer"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "google-maps",
    name: "Google Maps",
    description: "Geocoding, directions, places search and distance matrix via Google Maps.",
    longDesc: "Access Google Maps APIs: geocode addresses, get directions, search nearby places, calculate distance matrices and get place details.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-google-maps",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["maps", "location", "api", "official"]),
    tools: JSON.stringify(["maps_geocode", "maps_directions", "maps_search_places", "maps_distance_matrix"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 900,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-google-maps",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-google-maps"], env: { GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}" } }),
    envVars: JSON.stringify([{ name: "GOOGLE_MAPS_API_KEY", description: "Google Maps Platform API key", required: true }]),
  },
  {
    slug: "redis",
    name: "Redis",
    description: "Interact with Redis — get, set, list, and manage keys.",
    longDesc: "Full Redis operations: get/set keys, work with lists, hashes, sets and sorted sets. Supports TTL, patterns and pub/sub.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-redis",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["database", "redis", "cache", "official"]),
    tools: JSON.stringify(["set", "get", "delete", "list", "keys"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 700,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-redis",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-redis"], env: { REDIS_URL: "${REDIS_URL}" } }),
    envVars: JSON.stringify([{ name: "REDIS_URL", description: "Redis connection URL", required: true, example: "redis://localhost:6379" }]),
  },
  {
    slug: "google-drive",
    name: "Google Drive",
    description: "Search, read and manage files in Google Drive.",
    longDesc: "Access Google Drive: search files, read documents, spreadsheets and presentations, manage folders and permissions.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-gdrive",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["storage", "google", "files", "official"]),
    tools: JSON.stringify(["gdrive_search", "gdrive_read_file", "gdrive_list_files"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1100,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-gdrive",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-gdrive"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "aws-kb-retrieval",
    name: "AWS Knowledge Base",
    description: "Retrieve information from AWS Bedrock Knowledge Bases.",
    longDesc: "Query AWS Bedrock Knowledge Bases for RAG (Retrieval Augmented Generation) use cases. Supports hybrid search and filtering.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-aws-kb-retrieval",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["aws", "rag", "search", "official"]),
    tools: JSON.stringify(["retrieve"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 800,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-aws-kb-retrieval",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-aws-kb-retrieval"], env: { AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}", AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}", AWS_REGION: "${AWS_REGION}" } }),
    envVars: JSON.stringify([
      { name: "AWS_ACCESS_KEY_ID", description: "AWS Access Key ID", required: true },
      { name: "AWS_SECRET_ACCESS_KEY", description: "AWS Secret Access Key", required: true },
      { name: "AWS_REGION", description: "AWS Region", required: true, example: "us-east-1" },
    ]),
  },
  {
    slug: "everything",
    name: "Everything",
    description: "Test MCP server with all tool types — useful for development and testing.",
    longDesc: "A comprehensive test server that implements every MCP feature: prompts, resources, tools of all types. Ideal for testing MCP clients.",
    repoUrl: "https://github.com/modelcontextprotocol/servers",
    npmPackage: "@modelcontextprotocol/server-everything",
    authorName: "Anthropic",
    authorUrl: "https://anthropic.com",
    license: "MIT",
    version: "0.6.2",
    tags: JSON.stringify(["testing", "development", "official"]),
    tools: JSON.stringify(["echo", "add", "long_running_operation", "print_env", "sample_llm"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 600,
    verified: true,
    featured: false,
    category: "official",
    installCmd: "npx -y @modelcontextprotocol/server-everything",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@modelcontextprotocol/server-everything"] }),
    envVars: JSON.stringify([]),
  },

  // ─── COMUNIDAD ─────────────────────────────────────────────────────────────
  {
    slug: "playwright",
    name: "Playwright",
    description: "Browser automation with Playwright — multi-browser support.",
    longDesc: "Automate Chromium, Firefox and WebKit with Playwright. Navigate pages, interact with elements, capture screenshots and run accessibility tests.",
    repoUrl: "https://github.com/microsoft/playwright-mcp",
    npmPackage: "@playwright/mcp",
    authorName: "Microsoft",
    license: "Apache-2.0",
    version: "0.0.20",
    tags: JSON.stringify(["browser", "automation", "testing", "community"]),
    tools: JSON.stringify(["browser_navigate", "browser_click", "browser_screenshot", "browser_fill", "browser_snapshot"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 4100,
    verified: true,
    featured: true,
    category: "community",
    installCmd: "npx -y @playwright/mcp",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@playwright/mcp"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "notion",
    name: "Notion",
    description: "Read and write Notion pages, databases, and blocks.",
    longDesc: "Full Notion integration: read pages, create and update content, query databases, search your workspace and manage blocks.",
    repoUrl: "https://github.com/makenotion/notion-mcp-server",
    npmPackage: "@notionhq/notion-mcp-server",
    authorName: "Notion",
    license: "MIT",
    version: "1.0.0",
    tags: JSON.stringify(["productivity", "notion", "api", "community"]),
    tools: JSON.stringify(["notion_search", "notion_get_page", "notion_create_page", "notion_update_page", "notion_query_database"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1800,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y @notionhq/notion-mcp-server",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@notionhq/notion-mcp-server"], env: { OPENAPI_MCP_HEADERS: '{"Authorization": "Bearer ${NOTION_API_KEY}", "Notion-Version": "2022-06-28"}' } }),
    envVars: JSON.stringify([{ name: "NOTION_API_KEY", description: "Notion Internal Integration Secret", required: true, example: "secret_..." }]),
  },
  {
    slug: "linear",
    name: "Linear",
    description: "Manage issues, projects, and cycles in Linear.",
    longDesc: "Integrate Linear into your AI workflow: create and update issues, manage projects and cycles, search across your workspace.",
    repoUrl: "https://github.com/linear/linear-mcp",
    npmPackage: "@linear/linear-mcp",
    authorName: "Linear",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["project-management", "linear", "api", "community"]),
    tools: JSON.stringify(["create_issue", "update_issue", "list_issues", "search_issues", "list_projects"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1200,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y @linear/linear-mcp",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@linear/linear-mcp"], env: { LINEAR_API_KEY: "${LINEAR_API_KEY}" } }),
    envVars: JSON.stringify([{ name: "LINEAR_API_KEY", description: "Linear Personal API key", required: true, example: "lin_api_..." }]),
  },
  {
    slug: "stripe",
    name: "Stripe",
    description: "Interact with Stripe — customers, payments, subscriptions and more.",
    longDesc: "Access the Stripe API to manage customers, payments, subscriptions, invoices and products. Read-only by default for safety.",
    repoUrl: "https://github.com/stripe/agent-toolkit",
    npmPackage: "@stripe/mcp",
    authorName: "Stripe",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["payments", "stripe", "api", "community"]),
    tools: JSON.stringify(["list_customers", "create_customer", "list_payments", "list_subscriptions", "create_invoice"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 900,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y @stripe/mcp",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@stripe/mcp", "--tools=all"], env: { STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}" } }),
    envVars: JSON.stringify([{ name: "STRIPE_SECRET_KEY", description: "Stripe secret API key (usa test key para desarrollo)", required: true, example: "sk_test_..." }]),
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    description: "Manage Cloudflare Workers, KV, R2, D1 and more.",
    longDesc: "Deploy and manage Cloudflare resources: Workers scripts, KV namespaces, R2 buckets, D1 databases, and DNS records.",
    repoUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    npmPackage: "@cloudflare/mcp-server-cloudflare",
    authorName: "Cloudflare",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["cloud", "cloudflare", "serverless", "community"]),
    tools: JSON.stringify(["worker_list", "worker_deploy", "kv_get", "kv_put", "r2_list", "d1_query"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1500,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y @cloudflare/mcp-server-cloudflare",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@cloudflare/mcp-server-cloudflare"], env: { CLOUDFLARE_API_TOKEN: "${CLOUDFLARE_API_TOKEN}", CLOUDFLARE_ACCOUNT_ID: "${CLOUDFLARE_ACCOUNT_ID}" } }),
    envVars: JSON.stringify([
      { name: "CLOUDFLARE_API_TOKEN", description: "Cloudflare API Token", required: true },
      { name: "CLOUDFLARE_ACCOUNT_ID", description: "Cloudflare Account ID", required: true },
    ]),
  },
  {
    slug: "docker",
    name: "Docker",
    description: "Manage Docker containers, images, volumes and networks.",
    longDesc: "Control your Docker environment: list and manage containers, pull images, inspect volumes, view logs and manage networks.",
    repoUrl: "https://github.com/docker/mcp-servers",
    npmPackage: "docker-mcp",
    authorName: "Docker",
    license: "Apache-2.0",
    version: "0.1.0",
    tags: JSON.stringify(["devops", "docker", "containers", "community"]),
    tools: JSON.stringify(["list_containers", "start_container", "stop_container", "pull_image", "get_logs", "run_container"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1100,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y docker-mcp",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "docker-mcp"] }),
    envVars: JSON.stringify([]),
  },
  {
    slug: "supabase",
    name: "Supabase",
    description: "Manage Supabase projects, tables, edge functions and storage.",
    longDesc: "Full Supabase integration: query databases, manage tables and RLS policies, deploy edge functions, manage storage buckets and auth users.",
    repoUrl: "https://github.com/supabase-community/supabase-mcp",
    npmPackage: "@supabase/mcp-server-supabase",
    authorName: "Supabase",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["database", "supabase", "backend", "community"]),
    tools: JSON.stringify(["list_tables", "execute_sql", "list_edge_functions", "deploy_edge_function", "list_storage_buckets"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 1300,
    verified: true,
    featured: false,
    category: "community",
    installCmd: "npx -y @supabase/mcp-server-supabase",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@supabase/mcp-server-supabase"], env: { SUPABASE_URL: "${SUPABASE_URL}", SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY}" } }),
    envVars: JSON.stringify([
      { name: "SUPABASE_URL", description: "Supabase project URL", required: true, example: "https://xxx.supabase.co" },
      { name: "SUPABASE_SERVICE_ROLE_KEY", description: "Supabase service role key (secret)", required: true },
    ]),
  },
  {
    slug: "vercel",
    name: "Vercel",
    description: "Deploy and manage Vercel projects, deployments and domains.",
    longDesc: "Control your Vercel infrastructure: list and trigger deployments, manage environment variables, domains and team members.",
    repoUrl: "https://github.com/vercel/vercel-mcp",
    npmPackage: "vercel-mcp",
    authorName: "Vercel",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["deployment", "vercel", "cloud", "community"]),
    tools: JSON.stringify(["list_deployments", "create_deployment", "list_projects", "get_env_vars", "list_domains"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 950,
    verified: false,
    featured: false,
    category: "community",
    installCmd: "npx -y vercel-mcp",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "vercel-mcp"], env: { VERCEL_TOKEN: "${VERCEL_TOKEN}" } }),
    envVars: JSON.stringify([{ name: "VERCEL_TOKEN", description: "Vercel API token", required: true }]),
  },
  {
    slug: "jira",
    name: "Jira",
    description: "Manage Jira issues, sprints and projects from your AI assistant.",
    longDesc: "Full Jira integration: create and update issues, manage sprints, search with JQL, add comments and transition issue statuses.",
    repoUrl: "https://github.com/sooperset/mcp-atlassian",
    npmPackage: "mcp-atlassian",
    authorName: "sooperset",
    license: "MIT",
    version: "0.9.0",
    tags: JSON.stringify(["project-management", "jira", "atlassian", "community"]),
    tools: JSON.stringify(["jira_get_issue", "jira_create_issue", "jira_update_issue", "jira_search_issues", "jira_add_comment"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 600,
    verified: false,
    featured: false,
    category: "community",
    installCmd: "npx -y mcp-atlassian",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "mcp-atlassian"], env: { JIRA_URL: "${JIRA_URL}", JIRA_EMAIL: "${JIRA_EMAIL}", JIRA_API_TOKEN: "${JIRA_API_TOKEN}" } }),
    envVars: JSON.stringify([
      { name: "JIRA_URL", description: "Jira instance URL", required: true, example: "https://mycompany.atlassian.net" },
      { name: "JIRA_EMAIL", description: "Jira account email", required: true },
      { name: "JIRA_API_TOKEN", description: "Jira API token", required: true },
    ]),
  },
  {
    slug: "sentry",
    name: "Sentry",
    description: "Query Sentry issues, events and releases from your AI assistant.",
    longDesc: "Access Sentry error tracking data: list issues, inspect events, check releases and get stack traces without leaving your workflow.",
    repoUrl: "https://github.com/getsentry/sentry-mcp",
    npmPackage: "@sentry/mcp-server",
    authorName: "Sentry",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["monitoring", "errors", "api", "community"]),
    tools: JSON.stringify(["list_issues", "get_issue", "list_events", "list_releases"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 700,
    verified: false,
    featured: false,
    category: "community",
    installCmd: "npx -y @sentry/mcp-server",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@sentry/mcp-server"], env: { SENTRY_AUTH_TOKEN: "${SENTRY_AUTH_TOKEN}", SENTRY_ORG: "${SENTRY_ORG}" } }),
    envVars: JSON.stringify([
      { name: "SENTRY_AUTH_TOKEN", description: "Sentry Auth Token", required: true },
      { name: "SENTRY_ORG", description: "Sentry organization slug", required: true, example: "my-org" },
    ]),
  },
  {
    slug: "mysql",
    name: "MySQL",
    description: "Query MySQL and MariaDB databases with schema inspection.",
    longDesc: "Connect to MySQL or MariaDB databases, run SQL queries, inspect schemas and explore table structures.",
    repoUrl: "https://github.com/benborla/mcp-server-mysql",
    npmPackage: "mcp-server-mysql",
    authorName: "benborla",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["database", "sql", "mysql", "community"]),
    tools: JSON.stringify(["mysql_query", "mysql_list_tables", "mysql_describe_table"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 500,
    verified: false,
    featured: false,
    category: "community",
    installCmd: "npx -y mcp-server-mysql",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "mcp-server-mysql"], env: { MYSQL_HOST: "${MYSQL_HOST}", MYSQL_USER: "${MYSQL_USER}", MYSQL_PASSWORD: "${MYSQL_PASSWORD}", MYSQL_DATABASE: "${MYSQL_DATABASE}" } }),
    envVars: JSON.stringify([
      { name: "MYSQL_HOST", description: "MySQL host", required: true, example: "localhost" },
      { name: "MYSQL_USER", description: "MySQL user", required: true },
      { name: "MYSQL_PASSWORD", description: "MySQL password", required: true },
      { name: "MYSQL_DATABASE", description: "Database name", required: true },
    ]),
  },
  {
    slug: "elasticsearch",
    name: "Elasticsearch",
    description: "Search and query Elasticsearch indices.",
    longDesc: "Query Elasticsearch clusters: full-text search, aggregations, index management and document operations.",
    repoUrl: "https://github.com/elastic/mcp-server-elasticsearch",
    npmPackage: "@elastic/mcp-server-elasticsearch",
    authorName: "Elastic",
    license: "Apache-2.0",
    version: "0.1.0",
    tags: JSON.stringify(["search", "database", "elasticsearch", "community"]),
    tools: JSON.stringify(["search", "index_document", "list_indices", "get_mapping"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 450,
    verified: false,
    featured: false,
    category: "community",
    installCmd: "npx -y @elastic/mcp-server-elasticsearch",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "@elastic/mcp-server-elasticsearch"], env: { ELASTICSEARCH_URL: "${ELASTICSEARCH_URL}", ELASTICSEARCH_API_KEY: "${ELASTICSEARCH_API_KEY}" } }),
    envVars: JSON.stringify([
      { name: "ELASTICSEARCH_URL", description: "Elasticsearch cluster URL", required: true, example: "https://my-cluster.es.io" },
      { name: "ELASTICSEARCH_API_KEY", description: "Elasticsearch API Key", required: false },
    ]),
  },
  {
    slug: "context-pilot",
    name: "Context Pilot",
    description: "Intelligent context middleware — semantic search and memory for your codebase.",
    longDesc: "Indexes your codebase with embeddings, builds a dependency graph, and injects relevant context dynamically. Keeps architectural decisions persistent across sessions.",
    repoUrl: "https://github.com/diegotorres/context-pilot",
    authorName: "Diego",
    license: "MIT",
    version: "0.1.0",
    tags: JSON.stringify(["context", "embeddings", "memory", "community"]),
    tools: JSON.stringify(["query_context", "index_project", "remember", "get_graph", "search_code"]),
    clients: JSON.stringify(["claude-code", "cursor", "continue"]),
    transport: "stdio",
    stars: 420,
    verified: false,
    featured: true,
    category: "community",
    installCmd: "npx -y context-pilot serve",
    configJson: JSON.stringify({ command: "npx", args: ["-y", "context-pilot", "serve"] }),
    envVars: JSON.stringify([]),
  },
];

async function main() {
  console.log(`Seeding MCPHub with ${servers.length} servers...`);
  for (const server of servers) {
    await prisma.server.upsert({
      where: { slug: server.slug },
      update: server,
      create: server,
    });
    console.log("  ✓", server.name);
  }
  console.log(`\nDone! Total: ${servers.length} servers.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
